title: Rabbit Hole
description: 나도 만들어보는 Engineering Blog
author: Sasarino MARi
github: https://github.com/SasarinoMARi
about: 이것저것 만들어요
disqus_shortname: stackproblems
google_analytics: UA-XXXXXXXX-Y

enableTags: true
tagarray: []

collections:
  project:
    output: true
    permalink: /project/:path/

social:
    - icon: fa-twitter
      link: "https://twitter.com/SasarinoMARi"
    - icon: fa-github
      link: "https://github.com/SasarinoMARi"

share:
  twitter_username: github.io
  fb_appid: 1749788565247320

urls:
    - text: About Me
      url: /about/
    - text: My Projects
      url: /projects/
    - text: XML Feed
      url: /feed.xml

url: "https://sasarinomari.github.io/SasarinoMARi/"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/page/:num/"
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-gist

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: ['development']
